### ISSUE TITLE
Follow best-practice go layout

### ISSUE THREAD

**Issue by abergmeier** [codecutout/terraform-provider-powerbi#4]
For ease of starting with the provider, try to follow https://github.com/golang-standards/project-layout

**Comment by alex-davies** [comment]
Layout was mostly copied from other terraform providers as those standards would trump generic go standards. Where they do not put there packages under `/internal` but at the root level with the package name (`/powerbi` in my case). Test cases also normally sit alongside the resources rather than in a separate `/test` folder

Unlike the other providers I didn't have a website directory and went with the more golang compliant `/docs`, which is also where terraform are wanting providers to move their docs to

Also trimmed down on as much as possible as don't need a lot of the bloat present in other providers. I haven't bothered with a make file as you can build with the standard `go build` as such do not need a `/scripts` directory. This may change if hte size of the project warrants the complexity

docgen is a bit of an odd piece. Ideally it should be in a separate repo (even more ideally similar functionality would be provided by hashicorp) but needs access to internal resource schemas to pull out descriptions to put in the docs. As it is at the moment its a bit of cludge to fill a gap in documentation generation that exists in creating terraform providers


I guess the question is, is there anything specific that should be changed? and what advantages/disadvantages does that give us?

**Comment by alex-davies** [comment]
Updated layout to be more go friendly. Specifically added internal package and added all items within it
